language: node_js
node_js:
    - "lts/*"
sudo: false
addons:
    chrome: stable
    firefox: latest-esr

before_install:
    - npm install grunt-cli -g

script:
    - xvfb-run grunt ci

branches:
    only:
        - develop
